### ISSUE TITLE
ModuleNotFoundError: No module named 'discord_free_game_notifier'

### ISSUE THREAD

**Issue by kujodope** [TheLovinator1/discord-free-game-notifier#170]
Cant find the module
Used the pip installer but still it doesnt exist

pip install discord_free_game_notifier
ERROR: Could not find a version that satisfies the requirement discord_free_game_notifier (from versions: none)
ERROR: No matching distribution found for discord_free_game_notifier

**Comment by TheLovinator1** [comment]
Do you get this problem when running the program? Are you on Windows or Linux? How do you run the bot? In what directory do you run the bot?
