### ISSUE TITLE
id dosent detect epic free games ...

### ISSUE THREAD

**Issue by Kolhax** [TheLovinator1/discord-free-game-notifier#70]
![image](https://github.com/TheLovinator1/discord-free-game-notifier/assets/92904192/eaeb6932-24cf-4abc-a538-9e653c847935)
but gog and steam works

**Comment by TheLovinator1** [comment]
Hi, thanks for telling me this was broken.

This should be fixed now, there is a chance that this fix could trigger a false positive in a few weeks, but that should only be sent once if that happens.

Thanks again <3
